# Generated by Django 4.2.1 on 2023-08-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('guardians_contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('existing_condition', models.BooleanField()),
                ('existing_condition_details', models.TextField(blank=True)),
                ('taking_medications', models.BooleanField()),
                ('medications_list', models.TextField(blank=True)),
                ('known_allergies', models.BooleanField()),
                ('allergies_details', models.TextField(blank=True)),
                ('recent_illnesses', models.BooleanField()),
                ('recent_illnesses_details', models.TextField(blank=True)),
                ('surgeries_transfusions', models.BooleanField()),
                ('surgeries_transfusions_details', models.TextField(blank=True)),
                ('high_risk_behaviors', models.BooleanField()),
                ('high_risk_behaviors_details', models.TextField(blank=True)),
                ('recent_travel', models.BooleanField()),
                ('recent_travel_details', models.TextField(blank=True)),
                ('blood_type_known', models.BooleanField()),
                ('blood_type_details', models.TextField(blank=True)),
                ('consent', models.BooleanField()),
            ],
        ),
    ]
