# Generated by Django 4.2.1 on 2023-08-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='allergies_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood_type_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='blood_type_known',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='existing_condition',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='existing_condition_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='high_risk_behaviors',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='high_risk_behaviors_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='known_allergies',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='medications_list',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='recent_illnesses',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='recent_illnesses_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='recent_travel',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='recent_travel_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='surgeries_transfusions',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='surgeries_transfusions_details',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='taking_medications',
        ),
    ]
